name: compile java
on:
  pull_request:
    types:
      - opened
    branches:
      - main

jobs:
  compile-java:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    
    - name: Build Maven
      run: mvn clean -B package
